CREATE SCHEMA IF NOT EXISTS tpch_orc;

DROP TABLE IF EXISTS tpch_orc.lineitem;
DROP TABLE IF EXISTS tpch_orc.part;
DROP TABLE IF EXISTS tpch_orc.supplier;
DROP TABLE IF EXISTS tpch_orc.partsupp;
DROP TABLE IF EXISTS tpch_orc.nation;
DROP TABLE IF EXISTS tpch_orc.region;
DROP TABLE IF EXISTS tpch_orc.customer;
DROP TABLE IF EXISTS tpch_orc.orders;

-- create orc tables
CREATE TABLE tpch_orc.lineitem  STORED AS ORC AS SELECT * FROM default.lineitem;
CREATE TABLE tpch_orc.part 		STORED AS ORC AS SELECT * FROM default.part;
CREATE TABLE tpch_orc.supplier 	STORED AS ORC AS SELECT * FROM default.supplier;
CREATE TABLE tpch_orc.partsupp 	STORED AS ORC AS SELECT * FROM default.partsupp;
CREATE TABLE tpch_orc.nation 	STORED AS ORC AS SELECT * FROM default.nation;
CREATE TABLE tpch_orc.region    STORED AS ORC AS SELECT * FROM default.region;
CREATE TABLE tpch_orc.customer	STORED AS ORC AS SELECT * FROM default.customer;
CREATE TABLE tpch_orc.orders 	STORED AS ORC AS SELECT * FROM default.orders;

/*
USE tpch_orc;
ANALYZE TABLE lineitem COMPUTE STATISTICS;
ANALYZE TABLE lineitem COMPUTE STATISTICS FOR COLUMNS L_ORDERKEY, L_PARTKEY, L_SUPPKEY, L_LINENUMBER, L_QUANTITY, L_EXTENDEDPRICE, L_DISCOUNT, L_TAX, L_RETURNFLAG, L_LINESTATUS, L_SHIPDATE, L_COMMITDATE, L_RECEIPTDATE, L_SHIPINSTRUCT, L_SHIPMODE, L_COMMENT;
ANALYZE TABLE orders COMPUTE STATISTICS;
ANALYZE TABLE orders COMPUTE STATISTICS FOR COLUMNS O_ORDERKEY, O_CUSTKEY, O_ORDERSTATUS, O_TOTALPRICE, O_ORDERDATE, O_ORDERPRIORITY, O_CLERK, O_SHIPPRIORITY, O_COMMENT;
ANALYZE TABLE customer COMPUTE STATISTICS;
ANALYZE TABLE customer COMPUTE STATISTICS FOR COLUMNS C_CUSTKEY, C_NAME, C_ADDRESS, C_NATIONKEY, C_PHONE, C_ACCTBAL, C_MKTSEGMENT, C_COMMENT;
ANALYZE TABLE part COMPUTE STATISTICS;
ANALYZE TABLE part COMPUTE STATISTICS FOR COLUMNS P_PARTKEY, P_NAME, P_MFGR, P_BRAND, P_TYPE, P_SIZE, P_CONTAINER, P_RETAILPRICE, P_COMMENT;
ANALYZE TABLE partsupp COMPUTE STATISTICS;
ANALYZE TABLE partsupp COMPUTE STATISTICS FOR COLUMNS PS_PARTKEY, PS_SUPPKEY, PS_AVAILQTY, PS_SUPPLYCOST, PS_COMMENT;
ANALYZE TABLE supplier COMPUTE STATISTICS;
ANALYZE TABLE supplier COMPUTE STATISTICS FOR COLUMNS S_SUPPKEY, S_NAME, S_ADDRESS, S_NATIONKEY, S_PHONE, S_ACCTBAL, S_COMMENT;
ANALYZE TABLE nation COMPUTE STATISTICS;
ANALYZE TABLE nation COMPUTE STATISTICS FOR COLUMNS N_NATIONKEY, N_NAME, N_REGIONKEY, N_COMMENT;
ANALYZE TABLE region COMPUTE STATISTICS;
ANALYZE TABLE region COMPUTE STATISTICS FOR COLUMNS R_REGIONKEY, R_NAME, R_COMMENT;
*/