CREATE SCHEMA IF NOT EXISTS tpch_orc;

DROP TABLE IF EXISTS default.lineitem;
DROP TABLE IF EXISTS default.part;
DROP TABLE IF EXISTS default.supplier;
DROP TABLE IF EXISTS default.partsupp;
DROP TABLE IF EXISTS default.nation;
DROP TABLE IF EXISTS default.region;
DROP TABLE IF EXISTS default.customer;
DROP TABLE IF EXISTS default.orders;
DROP TABLE IF EXISTS tpch_orc.lineitem;
DROP TABLE IF EXISTS tpch_orc.part;
DROP TABLE IF EXISTS tpch_orc.supplier;
DROP TABLE IF EXISTS tpch_orc.partsupp;
DROP TABLE IF EXISTS tpch_orc.nation;
DROP TABLE IF EXISTS tpch_orc.region;
DROP TABLE IF EXISTS tpch_orc.customer;
DROP TABLE IF EXISTS tpch_orc.orders;

-- create tables and load data
CREATE EXTERNAL TABLE default.lineitem (
	L_ORDERKEY INT, 
	L_PARTKEY INT, 
	L_SUPPKEY INT, 
	L_LINENUMBER INT, 
	L_QUANTITY DOUBLE, 
	L_EXTENDEDPRICE DOUBLE, 
	L_DISCOUNT DOUBLE, 
	L_TAX DOUBLE, 
	L_RETURNFLAG STRING, 
	L_LINESTATUS STRING, 
	L_SHIPDATE STRING, 
	L_COMMITDATE STRING, 
	L_RECEIPTDATE STRING, 
	L_SHIPINSTRUCT STRING, 
	L_SHIPMODE STRING, 
	L_COMMENT STRING
) 
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' 
STORED AS TEXTFILE 
LOCATION '/tpch/100/lineitem';

CREATE EXTERNAL TABLE default.part (
	P_PARTKEY INT, 
	P_NAME STRING, 
	P_MFGR STRING, 
	P_BRAND STRING, 
	P_TYPE STRING, 
	P_SIZE INT, 
	P_CONTAINER STRING, 
	P_RETAILPRICE DOUBLE, 
	P_COMMENT STRING
) 
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' 
STORED AS TEXTFILE 
LOCATION '/tpch/100/part';

CREATE EXTERNAL TABLE default.supplier (
	S_SUPPKEY INT, 
	S_NAME STRING, 
	S_ADDRESS STRING, 
	S_NATIONKEY INT, 
	S_PHONE STRING, 
	S_ACCTBAL DOUBLE, 
	S_COMMENT STRING
) 
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' 
STORED AS TEXTFILE 
LOCATION '/tpch/100/supplier';

CREATE EXTERNAL TABLE default.partsupp (
	PS_PARTKEY INT, 
	PS_SUPPKEY INT, 
	PS_AVAILQTY INT, 
	PS_SUPPLYCOST DOUBLE, 
	PS_COMMENT STRING
) 
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' 
STORED AS TEXTFILE 
LOCATION'/tpch/100/partsupp';

CREATE EXTERNAL TABLE default.nation (
	N_NATIONKEY INT, 
	N_NAME STRING, 
	N_REGIONKEY INT, 
	N_COMMENT STRING
) 
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' 
STORED AS TEXTFILE 
LOCATION '/tpch/100/nation';

CREATE EXTERNAL TABLE default.region (
	R_REGIONKEY INT, 
	R_NAME STRING, 
	R_COMMENT STRING) 
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' 
STORED AS TEXTFILE 
LOCATION '/tpch/100/region';

CREATE EXTERNAL TABLE default.customer (
	C_CUSTKEY INT, 
	C_NAME STRING, 
	C_ADDRESS STRING, 
	C_NATIONKEY INT, 
	C_PHONE STRING, 
	C_ACCTBAL DOUBLE, 
	C_MKTSEGMENT STRING, 
	C_COMMENT STRING
) 
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' 
STORED AS TEXTFILE 
LOCATION '/tpch/100/customer';

CREATE EXTERNAL TABLE default.orders (
	O_ORDERKEY INT, 
	O_CUSTKEY INT, 
	O_ORDERSTATUS STRING, 
	O_TOTALPRICE DOUBLE, 
	O_ORDERDATE STRING, 
	O_ORDERPRIORITY STRING, 
	O_CLERK STRING, 
	O_SHIPPRIORITY INT, 
	O_COMMENT STRING
) 
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' 
STORED AS TEXTFILE 
LOCATION '/tpch/100/orders';

-- create orc tables
CREATE TABLE tpch_orc.lineitem  STORED AS ORC AS SELECT * FROM default.lineitem;
CREATE TABLE tpch_orc.part 		STORED AS ORC AS SELECT * FROM default.part;
CREATE TABLE tpch_orc.supplier 	STORED AS ORC AS SELECT * FROM default.supplier;
CREATE TABLE tpch_orc.partsupp 	STORED AS ORC AS SELECT * FROM default.partsupp;
CREATE TABLE tpch_orc.nation 	STORED AS ORC AS SELECT * FROM default.nation;
CREATE TABLE tpch_orc.region    STORED AS ORC AS SELECT * FROM default.region;
CREATE TABLE tpch_orc.customer	STORED AS ORC AS SELECT * FROM default.customer;
CREATE TABLE tpch_orc.orders 	STORED AS ORC AS SELECT * FROM default.orders;

-- create stats
ANALYZE TABLE default.lineitem COMPUTE STATISTICS;
ANALYZE TABLE default.lineitem COMPUTE STATISTICS FOR COLUMNS;
ANALYZE TABLE default.orders COMPUTE STATISTICS;
ANALYZE TABLE default.orders COMPUTE STATISTICS FOR COLUMNS;
ANALYZE TABLE default.customer COMPUTE STATISTICS;
ANALYZE TABLE default.customer COMPUTE STATISTICS FOR COLUMNS;
ANALYZE TABLE default.part COMPUTE STATISTICS;
ANALYZE TABLE default.part COMPUTE STATISTICS FOR COLUMNS;
ANALYZE TABLE default.partsupp COMPUTE STATISTICS;
ANALYZE TABLE default.partsupp COMPUTE STATISTICS FOR COLUMNS;
ANALYZE TABLE default.supplier COMPUTE STATISTICS;
ANALYZE TABLE default.supplier COMPUTE STATISTICS FOR COLUMNS;
ANALYZE TABLE default.nation COMPUTE STATISTICS;
ANALYZE TABLE default.nation COMPUTE STATISTICS FOR COLUMNS;
ANALYZE TABLE default.region COMPUTE STATISTICS;
ANALYZE TABLE default.region COMPUTE STATISTICS FOR COLUMNS;

ANALYZE TABLE tpch_orc.lineitem COMPUTE STATISTICS;
ANALYZE TABLE tpch_orc.lineitem COMPUTE STATISTICS FOR COLUMNS;
ANALYZE TABLE tpch_orc.orders COMPUTE STATISTICS;
ANALYZE TABLE tpch_orc.orders COMPUTE STATISTICS FOR COLUMNS;
ANALYZE TABLE tpch_orc.customer COMPUTE STATISTICS;
ANALYZE TABLE tpch_orc.customer COMPUTE STATISTICS FOR COLUMNS;
ANALYZE TABLE tpch_orc.part COMPUTE STATISTICS;
ANALYZE TABLE tpch_orc.part COMPUTE STATISTICS FOR COLUMNS;
ANALYZE TABLE tpch_orc.partsupp COMPUTE STATISTICS;
ANALYZE TABLE tpch_orc.partsupp COMPUTE STATISTICS FOR COLUMNS;
ANALYZE TABLE tpch_orc.supplier COMPUTE STATISTICS;
ANALYZE TABLE tpch_orc.supplier COMPUTE STATISTICS FOR COLUMNS;
ANALYZE TABLE tpch_orc.nation COMPUTE STATISTICS;
ANALYZE TABLE tpch_orc.nation COMPUTE STATISTICS FOR COLUMNS;
ANALYZE TABLE tpch_orc.region COMPUTE STATISTICS;
ANALYZE TABLE tpch_orc.region COMPUTE STATISTICS FOR COLUMNS;

-- Check table stats with SHOW TABLE STATS ...